Added Travis YAML file to support automated unit testing
prolificinteractive/simcoe pull request #12
Opened 2016-09-01 21:13 UTC by MichaelCampbell

2016-09-06 17:21 UTC, htinlinn commented
`mParticleTests` don't seem to be running on Travis; only `SimcoeTests` are being run...

2016-10-06 18:27 UTC, yoyoyoseob commented
How would I go about testing this?

2016-10-06 18:59 UTC, MichaelCampbell commented
@yoyoyoseob you can go to the `SimcoeTests` scheme and make sure the unit tests are running for both Simcoe and mParticle.  You can also try running `xcodebuild test -project Simcoe.xcodeproj -scheme SimcoeTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty` and see if that works locally.

It's still failing for me on Travis, so I don't think this is fully baked as yet.

2016-11-19 17:34 UTC, htinlinn requested changes

2016-11-19 17:34 UTC, htinlinn commented on .travis.yml
> +- set -o pipefail && xcodebuild test -project Simcoe.xcodeproj -scheme SimcoeTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' | xcpretty
Changing `-project Simcoe.xcodeproj` to `-workspace Simcoe.xcworkspace` seems to fix the issues on my local computer...

2016-11-23 02:44 UTC, htinlinn approved these changes

2016-11-23 02:44 UTC, htinlinn approved these changes

2016-11-23 02:46 UTC, merged